dados <- read.csv("dados_consumo_energia.csv", sep = ",", dec = ".", stringsAsFactors = TRUE)
print("summary")
print(summary(dados)) #summary
print("checando por ausências")
print(colSums(is.na(dados))) 
print("dados duplicados")
print(sum(duplicated(dados)))

#print(table(dados$num_moradores))
#print(table(dados$area_m2))
#print(table(dados$temperatura_media))
#print(table(dados$renda_familiar))
#print(table(dados$uso_ar_condicionado))
#print(table(dados$tipo_construcao))
#print(table(dados$isolamento_termico))
#print(table(dados$equipamentos_eletro))
print(mean(dados$num_moradores))
